apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rolling
  namespace: argocd
spec:
  destination:
    namespace: rolling
    server: https://kubernetes.default.svc
  project: demo
  source:
    helm:
      valueFiles:
        - values.yaml
    path: rolling
    repoURL: https://github.com/difranca/argo-rollouts-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen
  namespace: argocd
spec:
  destination:
    namespace: bluegreen
    server: https://kubernetes.default.svc
  project: demo
  source:
    helm:
      valueFiles:
        - values.yaml
    path: bluegreen
    repoURL: https://github.com/difranca/argo-rollouts-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary
  namespace: argocd
spec:
  destination:
    namespace: canary
    server: https://kubernetes.default.svc
  project: demo
  source:
    helm:
      valueFiles:
        - values.yaml
    path: canary
    repoURL: https://github.com/difranca/argo-rollouts-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ab
  namespace: argocd
spec:
  destination:
    namespace: ab
    server: https://kubernetes.default.svc
  project: demo
  source:
    helm:
      valueFiles:
        - values.yaml
    path: ab
    repoURL: https://github.com/difranca/argo-rollouts-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
