apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: demo
  source:
    helm:
      valueFiles:
        - values.yaml
    path: rolling
    repoURL: https://github.com/difranca/argo-rollouts-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
